### ISSUE TITLE
Question about the fully connected layer in the discriminator

### ISSUE THREAD

**Issue by gmingjie** [hmshan/MAP-NN#1]
Hi, 

When I printed the image shapes from each layer of the discriminator, I got something like this: 
(256, 32, 32, 64)
(256, 16, 16, 64)
(256, 16, 16, 128)
(256, 8, 8, 128)
(256, 8, 8, 256)
(256, 4, 4, 256)
(256, 4, 4, 1024)
(256, 4, 4, 1)
I'm using batch size = 256 and image patch size 32x32. 

I expect the last two output to have shapes (256, 1024) and (256, 1) after the dense layers. 
Should there be a reshaping operator on the conv2d output before sending it into the dense layers? 

Thanks!

**Comment by hmshan** [comment]
In this study, we did NOT use a reshape operator after the last convolutional layer. We empirically found that the network without the reshape operation in the discriminator converged faster and more stably. The reason seems that for supervised learning such a native output of the discriminator contains more information than the conventional output reshaped into a single value (Actually, we are exploring if this modification could improve the training of GAN in other tasks). However, we feel that for unsupervised/semi-supervised learning this reshape operation may need to be used.

**Comment by gmingjie** [comment]
Thank you for your reply. 
It seems that the idea is similar to a discriminator matrix people use in other tasks.
